import sys
import json

def generate_segment (out, items, prefix, counter):
    i = counter
    for item in items:
        out.write (prefix + item + "\t\t" + str(i) + "\n")
        i = i + 1
    out.write("\n")
    return i

def print_usage ():
        print("""Usage: python gen_defines.py in_file outfile prefix-type
Prefix-type can be "full", "short" or "none"
""")

def main ():

    args = sys.argv

    if len(args) != 4:
        print_usage()
        return 1

    in_file_name  = args[1]
    out_file_name = args[2]
    prefix_type   = args[3]

    f = open(in_file_name, "r")
    d = json.load(f)
    f.close()

    out = open(out_file_name, "w")

    prefix = "#define "

    if prefix_type == "full":
        prefix = prefix + d["prefix"] + "_" + d["type"] + "_"
    elif prefix_type == "short":
        prefix = prefix + d["type"] + "_"
    elif prefix_type == "none":
        pass
    else :
        print_usage()
        return 1

    out.write("""
/*************************************************************
 *
 *  This file is automatically generated.  Do not edit!
 *
 *  rather, edit "ast_defines.json" and generate using "gen_defines.py"
 *  in the ../utils folder
 *
 *************************************************************/


""")

    i = 0

    segments = d["segments"]
    for seg in segments:
        i = generate_segment(out, d[seg], prefix, i)

    out.close()


if __name__ == "__main__":
    main()
