
/*************************************************************
 *
 *  This file is automatically generated.  Do not edit!
 *
 *  rather, edit "ast_defines.json" and generate using "gen_defines.py"
 *  in the ../utils folder
 *
 *************************************************************/


#define AST_ASSIGN		0
#define AST_CALL_A		1
#define AST_CALL_B		2
#define AST_CALL_C		3
#define AST_CALL_D		4
#define AST_VAR_DECL		5
#define AST_IF		6
#define AST_BLOCK		7
#define AST_BREAK		8
#define AST_CONTINUE		9

#define AST_INT		10
#define AST_FLOAT		11
#define AST_SYMBOL		12
#define AST_STRING		13
#define AST_EXPR_ID		14
#define AST_NEG		15
#define AST_PLUS		16
#define AST_MINUS		17
#define AST_TIMES		18
#define AST_DIVIDE		19
#define AST_EQUALITY		20
#define AST_GREATER_THAN		21
#define AST_LESS_THAN		22

#define AST_STMT		23
#define AST_STMTS		24
#define AST_ARGLIST		25
#define AST_ID		26
#define AST_EXPR_PAIR		27
#define AST_TOP		28
#define AST_TOP_NODE		29
#define AST_PROC_DEF		30
