
/*************************************************************
 *
 *  This file is automatically generated.  Do not edit!
 *
 *  rather, edit "ast_defines.json" and generate using "ast_define_gen.py"
 *  in the ../utils folder
 *
 *************************************************************/


#define FIAL_PROC_DEF		0
#define FIAL_ASSIGN		1
#define FIAL_PROC_CALL		2
#define FIAL_VAR_DECL		3
#define FIAL_IF		4
#define FIAL_BLOCK		5
#define FIAL_BREAK		6
#define FIAL_CONTINUE		7

#define FIAL_INT		8
#define FIAL_FLOAT		9
#define FIAL_SYMBOL		10
#define FIAL_STRING		11
#define FIAL_EXPR_ID		12
#define FIAL_NEG		13
#define FIAL_PLUS		14
#define FIAL_MINUS		15
#define FIAL_TIMES		16
#define FIAL_DIVIDE		17
#define FIAL_EQUALITY		18
#define FIAL_GREATER_THAN		19
#define FIAL_LESS_THAN		20

#define FIAL_STMT		21
#define FIAL_STMTS		22
#define FIAL_BODY		23

