
/*************************************************************
 *
 *  This file is automatically generated.  Do not edit!
 *
 *  rather, edit "ast_defines.json" and generate using "gen_defines.py"
 *  in the ../utils folder
 *
 *************************************************************/


#define FIAL_AST_PROC_DEF		0
#define FIAL_AST_ASSIGN		1
#define FIAL_AST_PROC_CALL		2
#define FIAL_AST_VAR_DECL		3
#define FIAL_AST_IF		4
#define FIAL_AST_BLOCK		5
#define FIAL_AST_BREAK		6
#define FIAL_AST_CONTINUE		7

#define FIAL_AST_INT		8
#define FIAL_AST_FLOAT		9
#define FIAL_AST_SYMBOL		10
#define FIAL_AST_STRING		11
#define FIAL_AST_EXPR_ID		12
#define FIAL_AST_NEG		13
#define FIAL_AST_PLUS		14
#define FIAL_AST_MINUS		15
#define FIAL_AST_TIMES		16
#define FIAL_AST_DIVIDE		17
#define FIAL_AST_EQUALITY		18
#define FIAL_AST_GREATER_THAN		19
#define FIAL_AST_LESS_THAN		20

#define FIAL_AST_STMT		21
#define FIAL_AST_STMTS		22
#define FIAL_AST_BODY		23
